# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoanStar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoanStar
  pod 'web3swift', '~> 1.1.6'

  target 'LoanStarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoanStarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
